org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76
neo_version_range=[26.1.2.76,)
loader_version_range=[1,)

## Mod Properties
mod_id=haven_skyblock_builder
mod_name=HavenSkyblockBuilder
mod_license=All Rights Reserved
mod_version=0.2.1
mod_group_id=net.cathienova.haven_skyblock_builder
mod_authors=CathieNova
mod_description=Haven Skyblock Builder is a mod that gives you the ability to create your own skyblock islands.